import { expect, test } from 'bun:test'
import { verifyWestonScene } from './linux-scene'

// Shape is independently taken from Weston 13 libweston/compositor.c and
// shell-utils.c, rather than generated by the acceptance parser.
const scene = `Weston scene graph at 123.000000001:

Output 0 (screen0):
\tposition: (0, 0) -> (1180, 780)
\tmode: 1180x780@60.000Hz
\tscale: 1
\trepaint status: idle
\tHead 0 (screen0): connected

Layer 0 (pos 0x70000000):
\tView 0 (role xdg_toplevel, PID 1234, surface ID 17, top-level window 'Jazzkeys' of io.jazzkeys.desktop, 0xabc):
\t\tposition: (0, 0) -> (1180, 780)
\t\t[fully opaque]
\t\toutputs: 0 (screen0) (primary)

Layer 1 (pos 0x2):
\tView 0 (role kiosk-shell-background, PID 0, surface ID 0, kiosk shell background surface, 0xdef):
\t\tposition: (0, 0) -> (1180, 780)
\t\t[fully opaque]
\t\toutputs: 0 (screen0) (primary)
`
const expected = { pid: 1234, title: 'Jazzkeys', appId: 'io.jazzkeys.desktop', width: 1180, height: 780 }
test('dedicated Weston output requires the exact native process, app and full-output surface', () => {
  const report = verifyWestonScene(scene, expected)
  expect(report.passed).toBe(true)
  expect(report.clientSurfaceCount).toBe(1)
  expect(report.application.pid).toBe(1234)
})
test('other clients, cursor surfaces, altered labels, missing mapping and partial surfaces fail closed', () => {
  for (const bad of [
    scene.replace('PID 1234', 'PID 999'), scene.replace('io.jazzkeys.desktop', 'io.other.app'),
    scene.replace("'Jazzkeys'", "'Unrelated'"), scene.replace('role xdg_toplevel', 'role wl_pointer-cursor'),
    scene.replace('surface ID 17', 'surface ID 0'), scene.replace('\t\t[fully opaque]', '\t[surface is not mapped!]'),
    scene.replace('\t\tposition: (0, 0) -> (1180, 780)', '\t\tposition: (10, 0) -> (1180, 780)'),
    scene.replace('\t\t[fully opaque]', '\t\talpha: 0.900000'),
    scene.replace('kiosk shell background surface', 'unexpected panel'),
    scene.replace('PID 0, surface ID 0', 'PID 555, surface ID 20'),
    scene.replace('\tscale: 1', '\tscale: 2'), scene.replace('View 0 (role xdg_toplevel', 'View 0 (unknown xdg_toplevel'),
    scene.replace('Output 0 (screen0):', 'Output 1 (screen1):\nOutput 0 (screen0):'),
  ]) expect(() => verifyWestonScene(bad, expected)).toThrow()
})
